python/mysite/blog/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.index, name='index'),
	url(
		r'^view/(?P<slug>[\w-]+)/$', 
		views.view_post, 
		name='view_blog_post'),
	url(
		r'^category/(?P<slug>[\w-]+)/$', 
		views.view_category, 
		name='view_blog_category'),
	url(
		r'^archives/',
		views.view_archives,
		name='view_archives'),
	]
	

python/mysite/mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    url(r'^blog/', include('blog.urls', namespace="blog")),
	url(r'^polls/', include("polls.urls", namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
]

python/mysite/polls/urls.py
#polls/urls.py

from django.conf.urls import url

from . import views

urlpatterns = [
	url(r'^$', views.IndexView.as_view(), name='index'),
	url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
	url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
	url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

#cd C:\users\penga01\desktop\github\python\python\mysite

python/mysite/blog/models.py
from django.db import models
from django.db.models import permalink
# Create your models here.

class Category(models.Model):
	title = models.CharField(max_length=100, db_index=True)
	slug = models.SlugField(max_length=100, db_index=True)
	def __str__(self):
		return self.title
	class Meta:
		ordering = ['title']
		
class Blog(models.Model):
	title = models.CharField(max_length=100, unique=True)
	slug = models.SlugField(max_length=100, unique=True)
	author = models.CharField(max_length=100, default='yolo')
	body = models.TextField()
	posted = models.DateField(db_index=True, auto_now_add=True)
	category = models.ManyToManyField(Category)
	def __str__(self):
		return self.title
	
	

python/mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
	question_text = models.CharField(max_length=200)
	pub_date = models.DateTimeField('date published')
	def __str__(self):
		return self.question_text + " " + str(self.id)
		
class Choice(models.Model):
	question = models.ForeignKey(Question)
	choice_text = models.CharField(max_length=200)
	votes = models.IntegerField(default=0)
	def __str__(self):
		return self.choice_text
	

python/mysite/blog/views.py
from django.shortcuts import render_to_response, get_object_or_404, render
from django.core.paginator import Paginator, InvalidPage, EmptyPage, PageNotAnInteger
from django.core.urlresolvers import reverse
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse
import time
from calendar import month_name
from .models import Blog, Category

# Create your views here.
def index(request):
	categories = Category.objects.all().order_by('title')
	post_list = Blog.objects.all()[::-1]
	print(post_list)
	paginator = Paginator(post_list, 3)
	page = request.GET.get('page')
	try:
		posts = paginator.page(page)
	except PageNotAnInteger:
		posts = paginator.page(1)
	except EmptyPage:
		posts = paginator.page(pageinator.num_pages)
		
	context = {'categories': categories, 'posts':posts, }
	return render_to_response('blog/index.html', context)

	
def view_post(request, slug):
	post = get_object_or_404(Blog, slug=slug)
	try:
		previous_post = Blog.get_previous_by_posted(post)
	except ObjectDoesNotExist:
		previous_post = None
	try:
		next_post = Blog.get_next_by_posted(post)
	except ObjectDoesNotExist:
		next_post = None
	context = {
		'post':post, 
		'previous_post':previous_post,
		'next_post':next_post,
	}
	return render_to_response('blog/view_post.html', context)
	
def view_category(request, slug):
	category = get_object_or_404(Category, slug=slug)
	return render_to_response('blog/view_category.html', {
		'category': category,
		'posts': Blog.objects.filter(category=category),
	})
			

def view_archives(request):
	posts = Blog.objects.all().order_by('posted')[::-1]
	first = posts[0].posted
		
	return render_to_response('blog/view_archives.html', {
		'posts': posts,
	})

python/mysite/polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from .models import Choice, Question

class IndexView(generic.ListView):
	template_name = 'polls/index.html'
	context_object_name = 'latest_question_list'
	def get_queryset(self):
		return Question.objects.order_by('-pub_date')[:5]
		
class DetailView(generic.DetailView):
	model = Question
	template_name = 'polls/detail.html'
	
class ResultsView(generic.DetailView):
	model = Question
	template_name = 'polls/results.html'
	
	
def vote(request, question_id):
	p = get_object_or_404(Question, pk=question_id)
	try:
		selected_choice = p.choice_set.get(pk=request.POST['choice'])
	except (KeyError, Choice.DoesNotExist):
		return render(request, 'polls/detail.html', {
			'question': p,
			'error_message': "pls select a choice",
			})
	else:
		selected_choice.votes += 1
		selected_choice.save()
		return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

python/mysite/blog/templates/blog/base.html
<!--holy grail bby -->

<html>
<head>
	<meta name="viewport" content="width=device-width" />
	{% load staticfiles %}
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
	<link rel="stylesheet" type="text/css" href="{% static 'blog/style.css' %}"/>
	<link href='http://fonts.googleapis.com/css?family=Roboto:300' rel='stylesheet' type='text/css'>
	<link href='http://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
	<title>{% block head_title %}Babby's First Blog{% endblock %}</title>
	{% block scripts %} {% endblock %}
</head>
	
			
<body class="HolyGrail">
	<header>
		<h1>{% block title %}babby's first blog {% endblock %}</h1>
	</header>
	<div class="HolyGrail-body">
	{% block content %}
		
	{% endblock %}
	</div>
	
	<footer>
		{% block pagination %}
		{% endblock %}
		<a href="{% url 'blog:index' %}">Go Home</a>
		<h6>I made this!</h6>
	</footer>
	
</body>
</html>

python/mysite/blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% block scripts %}
<script>
$(document).ready(function(){
	$('.category-parent').click(function(){
		$('.category-nav').toggleClass('visible');
	});
});
</script>
{% endblock %}

{% block content %}
<nav class="HolyGrail-nav">
	<br />
	<h2><a href="#"> About </a></h2>
	<h2><a href="{% url 'blog:view_archives' %}"> Archives </a></h2>
	<div class="category-parent"><h2>Categories</h2>
	{% if categories %}
		<ul class="category-nav">
		{% for category in categories %}
			<li class="small-caps"><a href="{% url 'blog:view_blog_category' category.slug %}">{{ category.title }}</a></li>
		{% endfor %}
		</ul>
	{% endif %}
	</div>
	
	<h2><a href=#"> Contact </a></h2>
	
</nav>

<main class="HolyGrail-content">
	
	{% if posts %}
		
		{% for post in posts %}
		<div class="post">
			<h3><a href="view/{{ post.slug }}">{{ post.title|capfirst }}</a></h3>
			<br />
			<div class="font-roboto">{{ post.body|linebreaksbr|truncatewords:150 }}</div>
			<a href="view/{{ post.slug }}">continue</a>
			<br /><br />
			<h6>Written {{ post.posted }} by {{ post.author }}</h6>
			<h6>
				Posted in 
				{% for category in post.category.all %}
					<a href="{% url 'blog:view_blog_category' category.slug %}">{{ category }}</a> |
				{% endfor %}
			</h6>
		</div>
		{% endfor %}
		
	{% else %}
		<p>There's nothing yet</p>
	{% endif %}
	
	<!-- pagination -->
	
</main>
{% endblock %}

{% block pagination %}
	<div class="align-center">
	{% if posts.has_previous %}
		<a href="?page={{ posts.previous_page_number }}">previous</a>
	{% endif %}
	page {{ posts.number }} of {{posts.paginator.num_pages }}.
	{% if posts.has_next %}
		<a href="?page={{ posts.next_page_number }}">next</a>
	{% endif %}
	</div>
{% endblock %}

python/mysite/blog/templates/blog/view_archives.html
{% extends 'blog/base.html' %}
{% block head_title %}Archives {% endblock %}
{% block title %} Archives {% endblock %}

{% block content %}
	<div class="align-center post-body">
	{% if posts %}
	<ul>
		{% for post in posts %}
		<li><a href="{% url 'blog:view_blog_post' post.slug %}">{{ post.title }}</a> posted on {{ post.posted }}</li>
	
		{% endfor %}
	</ul>
	{% else %}
		<p>There's nothing yet</p>
	{% endif %}
	</div>
{% endblock %}

		

python/mysite/blog/templates/blog/view_category.html
{% extends 'blog/base.html' %}
{% block head_title %}Viewing category: {{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}

{% block content %}
	{% if posts %}
	<ul class="category-body">
	{% for post in posts %}
		<li class="align-center"><a  href="{% url 'blog:view_blog_post' post.slug %}">{{ post.title }} </a>posted by {{ post.author }} on {{ post.posted }}</li>
	{% endfor %}
		
	</ul>
	{% else %}
		<p>There's nothing yet</p>
	{% endif %}
{% endblock %}

python/mysite/blog/templates/blog/view_post.html
{% extends 'blog/base.html' %}
{% block head_title %}{{ post.title }}{% endblock %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
	<div class="post-body">
	<div class="align-center">
		Posted by {{ post.author }}
		<br />
		{{ post.posted }}
		<br />
		<br />
	</div>
		<div class="font-roboto">{{ post.body|linebreaksbr }}</div>
	<br />
	<br />
		<div class="post-navigation">
		{% if previous_post %}
			<a href="{% url 'blog:view_blog_post' previous_post.slug %}">< {{ previous_post.title }}</a>
		{% endif %}
		{% if previous_post and next_post %}
			*
		{% endif %}
		{% if next_post %}
			<a href="{% url 'blog:view_blog_post' next_post.slug %}">{{ next_post.title }} ></a>
		{% endif %}
		</div>
	</div>
{% endblock %}

python/mysite/polls/templates/polls/detail.html
<!--details.html-->

<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
	<input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
	<label for="choice{{ forloop.counter }}">{{ choice.choice_text }}
	</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
	
	

python/mysite/polls/templates/polls/index.html
<!--index.html-->

{% if latest_question_list %}
	<ul>
	{% for question in latest_question_list %}
		<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
	{% endfor %}
	</ul>
{% else %}
	<p>no polls are available</p>
{% endif %}

python/mysite/polls/templates/polls/results.html
<!--results.html-->

<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
	<li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>